name: 'Build Komodo'
on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'
      
      # Run static analysis
      - run: nimble check -Y
      
      # Build examples
      - name: "Build examples"
        run: |
          nimble develop
          cd examples/desktop
          nimble build -Y
      
      # Generate the Docs
      - name: Generate documentation
        run: |
          nimble doc --project --outdir:htmldocs --index:on ./src/komodo.nim --git.url:https://github.com/ExoKomodo/KomodoNim --git.commit:develop --git.devel:develop
          cp htmldocs/theindex.html htmldocs/index.html
          cp htmldocs/index.html htmldocs/404.html
          cp README.md ./htmldocs/README.md

      # Publish the website
      - name: GitHub Pages action
        if: ${{ github.ref == 'refs/heads/develop' }} # Publish only when the push is on develop
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: htmldocs
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          # Custom Domain
          # cname: somedomain.com